import{f as a,g as u}from"./assets/favorites-main-c4d1e5fe.js";import"./assets/vendor-0fffa566.js";const i=document.querySelector(".filters-box"),l=document.getElementById("cards-list"),d=i.querySelector(".filters-list-item"),f=d.dataset.filter,g=window.innerWidth;let o;p(g);const m=`https://energyflow.b.goit.study/api/filters?filter=${f}&page=1&limit=${o}`;function p(e){return e<768?o=8:(e>=768&&e<1024,o=12),o}async function h(){try{const t=await(await fetch(m)).json();t.results&&t.results.length>0?l.innerHTML=c(t.results):console.error("No exercises found.")}catch(e){console.error("Error fetching exercises:",e)}}function y(e){i.querySelectorAll(".filters-list-item").forEach(t=>{t.classList.remove("active_item")}),e.target.classList.add("active_item")}async function x(e){if(e.target.classList.contains("filters-list-item")){y(e);const r=`https://energyflow.b.goit.study/api/filters?filter=${e.target.dataset.filter}&page=1&limit=${o}`;try{const n=await(await fetch(r)).json();n.results&&n.results.length>0?l.innerHTML=c(n.results):console.error("No exercises found.")}catch(s){console.error("Error fetching exercises:",s)}}}function c(e){return e.reduce((t,r)=>t+`<li class="cards-list-item" style="background:linear-gradient(
      0deg,
      rgba(16, 16, 16, 0.7) 0%,
      rgba(16, 16, 16, 0.7) 100%
    ), url('${r.imgUrl}'),
    lightgray -16.825px -9.156px / 128.765% 116.922% no-repeat; background-size: cover;">
      <h3 class="card-title">${a(r.name)}</h3>
      <p class="card-subtitle">${r.filter}</p>
    </li>`,"")}document.addEventListener("DOMContentLoaded",h);i.addEventListener("click",x);async function q(){document.querySelector(".quote-info-content");const e=document.getElementById("quote-text"),t=document.querySelector(".quote-author");try{const{author:r,quote:s}=await u();e.textContent=s,t.textContent=`${r}`}catch(r){console.error("Error fetching or updating the quote:",r)}}document.addEventListener("DOMContentLoaded",()=>{q()});
//# sourceMappingURL=commonHelpers2.js.map
